

services:
  consul:
    image: hashicorp/consul
    container_name: consul
    ports:
      - "8500:8500"
      - "8600:8600"
    command: "agent -dev -node=cards2025 -bootstrap -ui -client=0.0.0.0"
    networks:
      - micro2025

  postgresrounds:
    image: postgres:15
    container_name: postgresrounds
    environment:
      - "POSTGRES_USER=serviceuser"
      - "POSTGRES_PASSWORD=servicepwd"
      - "POSTGRES_DB=rounds"
    ports:
      - "5433:5432"
    volumes:
      - rounds_data:/var/lib/postgresql/data
    networks:
      - micro2025

  postgresresolver:
    image: postgres:15
    container_name: postgresresolver
    environment:
      - "POSTGRES_USER=serviceuser"
      - "POSTGRES_PASSWORD=servicepwd"
      - "POSTGRES_DB=resolverdb"
    ports:
      - "5432:5432"
    volumes:
      - resolver_data:/var/lib/postgresql/data
    networks:
      - micro2025

  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - micro2025

  gateway:
    image: gateway:0.0.1-SNAPSHOT
    build: ./gateway
    container_name: gateway
    environment:
      - SPRING_PROFILE_ACTIVE=docker
      - SPRING_CLOUD_CONSUL_HOST=consul
    ports:
      - "8100:8100"
    depends_on:
      - consul
    networks:
      - micro2025

  round:
    image: round:0.0.1-SNAPSHOT
    build: ./round
    container_name: round
    expose:
      - "8000"
    depends_on:
      - consul
      - gateway
      - rabbitmq
      - postgresrounds
    networks:
      - micro2025

  deck:
    image: deck:0.0.1-SNAPSHOT
    build: ./deck
    container_name: deck
    environment:
      - SPRING_PROFILE_ACTIVE=docker
      - SPRING_CLOUD_CONSUL_HOST=consul
    depends_on:
      - consul
    expose:
      - "8001"
    networks:
      - micro2025

  automaplayer:
    image: automaplayer:0.0.1-SNAPSHOT
    build: ./automaplayer
    expose:
      - "8003"
    depends_on:
      - consul
    networks:
      - micro2025

  resolver:
    image: resolver:0.0.1-SNAPSHOT
    build: ./resolver
    depends_on:
      - consul
      - rabbitmq
      - postgresresolver
    expose:
      - "8006"
    networks:
      - micro2025

  frontend:
    image: frontend:0.1
    ports:
      - "5173:5173"
    networks:
      - micro2025


networks:
  micro2025:
    driver: bridge

volumes:
  rounds_data:
  resolver_data: