spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/resolverdb
    username: serviceuser
    password: servicepwd

  jpa:
    hibernate:
      ddl-auto: update

  config:
    import: "optional:consul:"

  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        register: true
        service-name: resolver
        health-check-path: /actuator/health
        health-check-interval: 10s

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

logging:
  level:
    org.springframework: INFO
