spring.application.name=automaplayer
server.port=8003

spring.config.import=optional:consul:
management.endpoints.web.exposure.include=health, info

spring.cloud.consul.host=consul
spring.cloud.consul.port=8500
