spring.application.name=resolver

server.port=8005

amqp.exchange.name=round.exchange
amqp.queue.name=rounds.complete
amqp.routing.key.complete=round.completed


spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672

spring.datasource.url=jdbc:postgresql://postgresresolver:5432/resolver
spring.datasource.username=serviceuser
spring.datasource.password=servicepwd
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect