spring.application.name=deck
server.port=8001
spring.config.import=optional:consul:
spring.cloud.consul.host=localhost
spring.cloud.consul.port=8500
spring.cloud.consul.discovery.service-name=deck-from-consul
spring.cloud.consul.discovery.instance-id="${spring.application.name}-${random.int[1000,9999]}"
spring.cloud.consul.config.enabled=true
spring.cloud.consul.config.format=yaml

logging.level.org.springframework.cloud.consul.config=DEBUG
management.endpoints.web.exposure.include=health,info