spring.application.name=round

server.port=8000

deck.client.host=http://gateway:8100/api/deck
automa.client.host=http://gateway:8100/api/automa

amqp.exchange.name=round.exchange

spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672

spring.datasource.url=jdbc:postgresql://postgresrounds:5432/rounds
spring.datasource.username=serviceuser
spring.datasource.password=servicepwd
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.config.import=optional:consul:

spring.cloud.consul.host=consul
spring.cloud.consul.port=8500

management.endpoints.web.exposure.include=health, info